apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter-peer
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 1.8.2
  name: node-exporter-peer
  namespace: observability-peer
spec:
  clusterIP: None
  ports:
  - name: https
    port: 9001
    targetPort: https
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter-peer
    app.kubernetes.io/part-of: kube-prometheus
