apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: prometheus-peer
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.48.0
  name: prometheus-peer
  namespace: observability-peer
spec:
  additionalScrapeConfigs:
    key: additional-scrape-configs.yaml
    name: additional-scrape-configs
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: prometheus
              app.kubernetes.io/instance: prometheus-peer
              app.kubernetes.io/name: prometheus
              app.kubernetes.io/part-of: kube-prometheus
          namespaces:
          - observability-peer
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - name: prometheus
    startupProbe:
      failureThreshold: 120
  enableAdminAPI: false
  enableFeatures:
  - memory-snapshot-on-shutdown
  - remote-write-receiver
  - exemplar-storage
  externalLabels:
    cluster: ${PEER_ID}
    env: ${PEER_ENVIRONMENT}
  image: quay.io/prometheus/prometheus:v2.48.0
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: prometheus-peer
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.48.0
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  remoteWrite:
  - basicAuth:
      password:
        key: password
        name: observability-peer-auth
      username:
        key: username
        name: observability-peer-auth
    headers:
      X-Scope-OrgID: ${PEER_ID}
    queueConfig:
      maxSamplesPerSend: 5000
    sendExemplars: true
    url: ${PEER_OBSERVER_URL}/api/v1/push
    writeRelabelConfigs:
    - action: labeldrop
      regex: pod_template_hash|controller_revision_hash|k8s_replicaset_name|k8s_pod_uid|instance
    - action: labeldrop
      regex: applications_argoproj_io_.*|kustomize.*
    - action: labeldrop
      regex: app_kubernetes_io_instance|app_kubernetes_io_version|app_kubernetes_io_component|app_kubernetes_io_part_of|app_kubernetes_io_managed_by|helm_sh_chart
    - action: labeldrop
      regex: linkerd_io_.*
  replicas: 1
  resources:
    requests:
      memory: 100Mi
  retention: 4d
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      role: no-match
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector: {}
  scrapeInterval: 60s
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-prometheus-peer
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  storage:
    volumeClaimTemplate:
      apiVersion: v1
      kind: PersistentVolumeClaim
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: ${PEER_PROMETHEUS_VOLUME_SIZE}Gi
  tsdb:
    outOfOrderTimeWindow: 5m
  version: 2.48.0
