apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: aws-node
  name: aws-node
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: cni-metrics-port
    port: 61678
    targetPort: 61678
  selector:
    app.kubernetes.io/name: aws-node
