apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics-peer
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.9.2
  name: kube-state-metrics-peer
  namespace: observability-peer
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 30s
    metricRelabelings:
    - action: drop
      regex: kube_endpoint_address_not_ready|kube_endpoint_address_available
      sourceLabels:
      - __name__
    - regex: (.+)
      sourceLabels:
      - label_cloud_google_com_gke_nodepool
      targetLabel: label_nodegroup
    - regex: (.+)
      sourceLabels:
      - label_eks_amazonaws_com_nodegroup
      targetLabel: label_nodegroup
    port: https-main
    relabelings:
    - action: labeldrop
      regex: (pod|service|endpoint|namespace)
    - action: replace
      regex: (.+)
      replacement: kube-state-metrics
      sourceLabels:
      - job
      targetLabel: job
    scheme: https
    scrapeTimeout: 30s
    tlsConfig:
      insecureSkipVerify: true
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https-self
    relabelings:
    - action: labeldrop
      regex: (pod|service|endpoint|namespace)
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kube-state-metrics-peer
      app.kubernetes.io/part-of: kube-prometheus
