apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: prometheus-peer
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.46.0
    prometheus: k8s
  name: prometheus-peer
  namespace: observability-peer
spec:
  additionalScrapeConfigs:
    key: additional-scrape-configs.yaml
    name: additional-scrape-configs
  enableFeatures:
  - auto-gomaxprocs
  - new-service-discovery-manager
  enableRemoteWriteReceiver: true
  externalLabels:
    cluster: ${PEER_ENVIRONMENT}-${PEER_CLUSTER}
    env: ${PEER_ENVIRONMENT}
  image: quay.io/prometheus/prometheus:v2.46.0
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: prometheus-peer
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.46.0
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  remoteWrite:
  - basicAuth:
      password:
        key: password
        name: observability-tenant-auth
      username:
        key: username
        name: observability-tenant-auth
    headers:
      X-Scope-OrgID: ${PEER_ENVIRONMENT}-${PEER_CLUSTER}
    queueConfig:
      maxSamplesPerSend: 5000
    sendExemplars: true
    url: ${PEER_OBSERVER_URL}/api/v1/push
    writeRelabelConfigs:
    - action: labeldrop
      regex: pod_template_hash|controller_revision_hash|k8s_replicaset_name|k8s_pod_uid
    - action: labeldrop
      regex: applications_argoproj_io*
    - action: labeldrop
      regex: app_kubernetes_io_instance|app_kubernetes_io_version|app_kubernetes_io_component|app_kubernetes_io_part_of|app_kubernetes_io_managed_by
    - action: labeldrop
      regex: linkerd_io_.*
  replicas: 1
  resources:
    requests:
      memory: 100Mi
  scrapeInterval: 60s
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-prometheus-peer
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: 2.46.0
